language: bash
script:
- "./uavo.sh https://bitbucket.org/librepilot/librepilot.git librepilot next"
- "./uavo.sh https://bitbucket.org/librepilot/librepilot.git librepilot tags/15.09"
- "./uavo.sh https://bitbucket.org/alessiomorale/librepilot.git librepilot amorale/LP-276_measurement_based_d_term"
- "./uavo.sh https://bitbucket.org/TheOtherCliff/librepilot.git librepilot theothercliff/LP-76_Port_Autotune_from_dRonin"
- "./uavo.sh https://bitbucket.org/TheOtherCliff/librepilot.git librepilot theothercliff/LP-225_sonar_support"
- "./uavo.sh https://bitbucket.org/m_thread/librepilot.git librepilot thread/Qt-5.6_Support_Mac"
- "./uavo.sh https://bitbucket.org/mkaduk/librepilot.git librepilot LP-286_taulabs_uavbrowser_filter"
before_install:
- chmod +x uavo.sh
addons:
  apt:
    packages:
    - libc6-i386
env:
  global:
  - GH_REF: github.com/MarcProe/lp2go-uavo.git
  - secure: MOOReVYdH77po14Au7l3XwxMlbfG9QY/AmvtjQJkMUG2QxbBKwQvpQGnINWhJ40nLcxCVXszo7DqOvCM1oTP+Rq1Wv+UONzEdRimL+2NZUKnsywkLp7lnUsZ1gQ+smhbRqocHGJuvIVoCktS7p0Q/GQyHwlrI2b9SIDnN8Tvfo9riXLfhy/fMsFPqePR+bp+1EmVci7LndAY5jK3Zom6InksNnoBUNEKaUpeAzF0riviHtkIobKH5gloYr6Yl1ncnT9GfMY4KlM8iOSy31JZ7YFmVkCOodUu4+Skzftg0lSVYKMhI8jzmtGS63HWE+twk0cz42ivOaWs5BTt4OrP927QY10A1T8fO9JJvAnKldjEsnTtr+rBaIBqH1PDJrQjgeaYQmrKDtWYprhtlQSF0DcX6ajmpVP69tJvJUzhtXf+NMYxc/wHSClEDmoSNS+H8L8f2BkgB4UOa+CkycyYLLIeUGPaKz9pLoDsgzrUNhkW6VooinKvnd6dOq6sT3ZqcNk7g7EcG70DhWYkLLBft13LeM+GH+acInqzvbXQjWrI/0cnsD/N/Mu/PHMghrK6qrABqH+BF4oZdG9gfpTmE3QB8rafIdjhhuWNqOPxyb+49Sm5WzYWwKu1LbDK+ivCYWDQq+JCDW3sYFhllBsr4t865E4sm/TpJq/dhK4v8aw=
  - secure: NDN2xKqRSpdwQEQEWDuEObTublqwMkOuvtUfpi9reJbJd5zvZxgSpqKF6ihezqMF+e8ax7/zrUHqQ+8h6WVulrNeDzXlATC53lZb3wdJqrDiUS7YmBbIrIdiAoKc2P2PSDf10Ul/Xo+rD3FKAaYrhlUByY3564dNp5IkiWeUa0QLbI6+djl0x5isOkw/5ZQIzQrVXoDAqzgSF66pBn9N70P/iTOA+HRuObCakHaCKZWnTLNceV7ahGL2IdIVyw4iWUKXPRPuU8HRlebYd2oiTenbwmz0J+88ZP28NivjWMYLS5BOxY3JbzL7kcN2Wd1CsUcdVos+RTLbDfoUb8oZHvMiOJ52kmczV0BaHfpQ0tAFl1ryvNMTOzW5KD/LD2GU91Y/fY44NFnmmao4TsBK+S8vQsHRtHcHJ9hxAZ7UCKlVQfURllVGVVt5N1VxtBlHOdN7AxLTUmtY2e5sMQGWdldU4oOfZLTqzS51/Rm2esXHxrZ8JL/EHn9E7d99FG9AhkGXiOqGDKiCfywhibQfExIi4eAwp8+VJwuI1ZRtnfQGKysgp7zPHZbwUHEXUPhTA2pGdPDZe8CYYOI/OypDl/YVQKVDT2T/c4uL94BKiKWULCmUudKeUJtgUD+mP6sAft+yKVAntK4Z13egRxSbv37K2Q3lVWwRJKilDKmIPtk=
  - secure: UZ7DZRVezBvAN1E24cgQa3rzBgshWhIfDrcOePM6viwE8dG2emoaVWDFgHlUZ9E4TCd2H0G1RxvcDwiZ57JGDGtF344k1yDV0Gql8riwq8EyoBxnKQVjvSd+R1LDD12mIc65DY7Gf7jzyCPu9Ulf2fLoxdLi7NCLqjycKDdJzmABn9YBN2IG5Fo1Cm3sRkVmHjkieLvr/hjwOF+T3614EB7Ye1Kd6wS0W3PtgUk9blhqs8W16URyNbhaPaT+ZIAfOvkRSyZoAuvLnxZvHs7adTMZhoKfYc6vVAEh06li52gWbW/eskazIlj2ButRrgRhtOMKNROrfzMV9D67sk3tELIO+NKgpSHKfjQXLj42YcpgpIn6qa7gPcHJewsSObpldGO+3N8IJfy6zjXHfJwvn7hbghfpC/gQS3PRiIanAUwj112nzi9pqIIzebzb1cHCoQgDXBr7OC6R1l+RjZtsxcErjyQyfQYTD0gcl6VcQlFBZvS61oC+3DLYD/NmbEI/7YSq4FLPo0GmNiSk8NxWR1rwvWZfW4QnL23MaKrRDeqsZ3DA+IavsGiP3ZZ6Awzk24Vgp7cBUgxBApg5JaGkJBiaAUCNiKSmeZeAX3Arg2xVpOEo7Erhxc73PUqMFXqz5eF5S80f95uQn48uhVRHnY6CoQVW0eHJzbzyxXKaOb8=
deploy:
  provider: bintray
  file: bintray.json
  user: marcproe
  key: $BINTRAY_API_KEY
